### ISSUE TITLE
Any pretrained model available for testing?

### ISSUE THREAD

**Issue by bimo-adiparwa** [Monu-Khicher-1/multi-stage-learning#1]
Hi, Author! I really interested with your paper.
Is there pretrained model available?
Thank you

**Comment by Monu-Khicher-1** [comment]
Hi @bimo-adiparwa!

Thank you for your interest in the paper! I’ve added the link to the pre-trained model weights in the README for easy access. You can find them [here](https://drive.google.com/drive/folders/1F6YgS3ayNfuHjjOwNMvWFpjY6IONsuhy?usp=drive_link).

Let me know if you have any further questions or need additional assistance.

**Comment by Monu-Khicher-1** [comment]
[weights link](https://drive.google.com/drive/folders/1F6YgS3ayNfuHjjOwNMvWFpjY6IONsuhy?usp=drive_link).
